# Async/await

Изучено: Yes

- **Async** - эта функция всегда возвращает промис. Значения других типов оборачиваются в завершившийся успешно промис автоматически.

```jsx
async function f() {
  return Promise.resolve(1); //явно возвращает промис 
}

f().then(alert); // 1
```

- **Await -** заставит интерпретатор JavaScript ждать до тех пор, пока промис справа от `await`
 не выполнится. После чего оно вернёт его результат, и выполнение кода продолжится.
    - НО!!! **пока** промис **не выполнится**, JS-движок **может** заниматься другими задачами: выполнять прочие скрипты, обрабатывать события и т.п.

```jsx
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("готово!"), 1000)
  });

  let result = await promise; // будет ждать, пока промис не выполнится (*)

  alert(result); // "готово!"
}

f();
```

---

***Обработка ошибок***

- Когда промис завершается успешно, `await promise`возвращает результат. Когда завершается с ошибкой – будет выброшено исключение. Как если бы на этом месте находилось выражение `throw`.

```jsx
async function f() {
  await Promise.reject(new Error("Упс!"));
}
```

- Есть отличие — промис завершиться с ошибкой **не сразу**, а через некоторое время.
- Такие ошибки нужно ловить через `try..catch`

```jsx
async function f() {

  try {
    let response = await fetch('http://no-such-url');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
```

- Если у нас нет `try..catch`, асинхронная функция будет возвращать завершившийся с ошибкой промис (в состоянии `rejected`).