# Промисы

Изучено: Yes

***Асинхронное программирование с помощью коллбек-функций***

```jsx
function loadScript (src, callback) {
    let script = document.createElement ('script');
    script.src = src;
    script.onload = () => callback(script);
    document.head.append(script);
}

loadScript ('https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.js', script => {
    console.log(`Здорово, скрипт ${script.src} загрузился`);
    console.log( _ );
})
```

- Событие `onload` - оно в основном выполняет функцию после загрузки и выполнения скрипта.
- В функции, которые выполняют какие-либо асинхронные операции, передаётся аргумент `callback`— функция, которая будет вызвана по завершению асинхронного действия.

---

***Промис***

```jsx
let promise = new Promise(function(resolve, reject) {
  // функция-исполнитель (executor)
  // "певец"
});
```

Когда он получает результат, сейчас или позже – не важно, он должен вызвать один из этих колбэков:

- `resolve(value)` — если работа завершилась успешно, с результатом `value`.
- `reject(error)` — если произошла ошибка, `error` – объект ошибки.

`resolve` и `reject` — это функции, встроенные в JavaScript, поэтому нам не нужно их писать.

При этом созданный **объект promise** будет иметь свойства 

- `state` («состояние») — вначале `"pending"` («ожидание»), потом меняется на `"fulfilled"` («выполнено успешно») при вызове `resolve` или на `"rejected"` («выполнено с ошибкой») при вызове `reject`.
- `result` («результат») — вначале `undefined`, далее изменяется на `value` при вызове `resolve(value)` или на `error` при вызове `reject(error)`.

**Таким образом**, при исполнении **функции-исполнителя** вызовется **одна и только одна** из двух колбек-функций → которые изменят состояние промиса. В последующем ничто не сможет изменить состояние промиса. 

---

[***Потребители: then, catch***](https://learn.javascript.ru/promise-basics#potrebiteli-then-catch)

***Метод then***

```jsx
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("done!"), 1000);
});

// resolve запустит первую функцию, переданную в .then
promise.then(
  result => alert(result), // выведет "done!" через одну секунду
  error => alert(error) // не будет запущена
);
```

- Первый аргумент метода `.then` – функция, которая выполняется, когда промис переходит в состояние **«выполнен успешно»**, и получает результат.
- Второй аргумент `.then` – функция, которая выполняется, когда промис переходит в состояние **«выполнен с ошибкой»**, и получает ошибку.

***Метод catch***

```jsx
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("Ошибка!")), 1000);
});

// .catch(f) это то же самое, что promise.then(null, f)
promise.catch(alert); // выведет "Error: Ошибка!" спустя одну секунду
```

- Если мы хотели бы только обработать ошибку, можно воспользоваться методом `.catch(errorHandlingFunction)`
- Вызов `.catch(f)` – это сокращённый, «укороченный» вариант `.then(null, f)`.

---

***Метод очистки: finally*** 

- Идея `finally` состоит в том, чтобы настроить обработчик для выполнения очистки/доведения после завершения предыдущих операций.
- `f` выполнится в любом случае, когда промис завершится: успешно или с ошибкой.

*Пример — остановка индикаторов загрузки, закрытие больше не нужных соединений и т.д*

```jsx
new Promise((resolve, reject) => {
  setTimeout(() => resolve("value"), 2000);
})
  .finally(() => alert("Промис завершён")) // срабатывает первым
  .then(result => alert(result)); // <-- .then показывает "value"
```

*Особенности:* 

1. не имеет аргументов, не знает как завершился промис (результат). Выполнит общие действия. 
2. Он пропускает результат промиса дальше к другим обработчикам, не задействуя результат 
3. Он не должен ничего возвращать. Если такое происходит, то он передает ошибку близжаейшему обработчику ошибок.

---

***Способы исправления ошибки***

- Если наш промис **завершил** свое выполнение **с ошибкой**, то выполнение кода сразу перейдет к тому `then`, в котором есть функция-обработчик ошибки, либо в первому `catch`, смотря что встретится раньше.
- Функция-обработчик имеет **два варианта действий:** если она **справилась** с исключительной ситуацией, то может **вернуть результат** через `return` и выполнение продолжится дальше по цепочке. Если же она **не справилась** с ошибкой, то может или ничего не возвращать, или выбросить исключение через `throw`.
- `catch`нужен именно для диагностики ошибки: она решаема или нет.

---

***Promise API*** 

В классе `Promise` есть 6 статических методов.

1. `Promise.all`
    - позволяет выполнить код по окончанию всех промисов, переданных ему в виде массива
    - результатом этого промиса будет массив результатов всех переданных промисов (порядок результатов соответствует порядку промисов в массиве)
    - **`Promise.all(iterable)` разрешает передавать не-промисы в `iterable` (перебираемом объекте)**
    
    ```jsx
    let urls = [
      'https://api.github.com/users/iliakan',
      'https://api.github.com/users/remy',
      'https://api.github.com/users/jeresig'
    ];
    
    // Преобразуем каждый URL в промис, возвращённый fetch
    let requests = urls.map(url => fetch(url));
    
    // Promise.all будет ожидать выполнения всех промисов
    Promise.all(requests)
      .then(responses => responses.forEach(
        response => alert(`${response.url}: ${response.status}`)
      ));
    ```
    
2. `Promise.race`
    - ждёт только первый ***выполненный*** промис, из которого берёт результат (или ошибку).
    - результатом этого промиса будет массив с результатом первого сработавшего промиса.

Оба возвращают новый массив

Если хотя бы один из промисов в массиве будет отклонен, то промис с результатом сразу же перейдет в состояние `rejected`.

```jsx
Promise.all(promises).then(function(res) {
	console.log(res);
}).catch(function(err) {
	console.log(err);
});
```

1.  `Promise.allSettled`
    - всегда ждёт завершения всех промисов, не останавливается если имеется ошибка
    - результат записывается в виде
    
    ```jsx
    {status:"fulfilled", value:результат} для успешных завершений,
    {status:"rejected", reason:ошибка} для ошибок.
    ```
    
2. `Promise.any`
    - ждёт только первый ***успешно выполненный*** промис, из которого берёт результат.
    
    ```jsx
    Promise.any([
      new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ошибка!")), 1000)),
      new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ещё одна ошибка!")), 2000))
    ]).catch(error => {
      console.log(error.constructor.name); // AggregateError
      console.log(error.errors[0]); // Error: Ошибка!
      console.log(error.errors[1]); // Error: Ещё одна ошибка!
    });
    ```
    

---

***Создание сработавших промисов в JS***

- использование уже выполненного промиса
- существует два метода:
    1. `Promise.resolve` - создает выполненный успешно промис;
    2. `Promise.reject` - создает отклоненный промис;
    

Используем в том случае, когда мы, например, хотели бы проверить входящие данные в промис на условия. И если произойдет ошибка - создать другой промис, например с числом. 

```jsx
function func(num) {
	if (num > 0) {
		return new Promise(function(resolve) {
			setTimeout(function() {
				resolve(num * num);
			}, 3000);
		});
	} else if (num === 0) {
		return Promise.resolve(0);
	} else {
		return Promise.reject('incorrect number'); // вернем отклоненный 
			промис 
	}
}
```

---

***Промисификация асинхронного кода в JS***

- создание оболочки в виде промиса над определенным функционалом
- Например, при загрузке кода